Repository apache/skywalking-client-js, pull requests merged in 2021-04, with the labels that each got.

#48 feat: get response.body as a stream with the fetch API
  dist/licenses/LICENSES-fetch.txt
  package-lock.json
  package.json
  src/interceptors/fetch.js
  src/interceptors/xhr.ts
  src/trace/interceptors/fetch.ts
  src/trace/interceptors/xhr.ts
  src/trace/segment.ts
Labels: enhancement

#49 feat: Support reporting multiple logs
  src/errors/ajax.ts
  src/services/base.ts
  src/services/report.ts
  src/services/task.ts
  src/trace/interceptors/fetch.ts
Labels: enhancement

#50 fix typo
  src/services/base.ts
  src/services/task.ts
  src/services/types.d.ts
  src/trace/interceptors/fetch.ts
  src/trace/interceptors/xhr.ts
  src/trace/segment.ts
  src/trace/type.d.ts
Labels: chore

#51 fix: update peer in fetch
  src/trace/interceptors/fetch.ts
Labels: bug

#53 fix: reporting errors when close pages
  src/services/base.ts
  src/services/task.ts
Labels: bug

#54 docs: update CHANGES and version
  CHANGES.md
  package.json
Labels: documentation
