Repository apache/skywalking-client-js, pull requests merged in 2021-07, with the labels that each got.

#62 fix: catch errors for http requests
  README.md
  src/errors/ajax.ts
  src/services/base.ts
  src/trace/interceptors/fetch.ts
Labels: bug

#63 fix: the firstReportedError is calculated with more types of errors
  src/services/base.ts
  src/trace/interceptors/fetch.ts
Labels: bug

#64 docs: update version and changes
  CHANGES.md
  package-lock.json
  package.json
Labels: documentation

#65 feat: support setting time interval to report segments
  CHANGES.md
  README.md
  src/monitor.ts
  src/services/base.ts
  src/trace/segment.ts
  src/types.d.ts
Labels: enhancement

#68 fix apache/skywalking#7335
  CHANGES.md
  src/trace/interceptors/fetch.ts
  src/trace/interceptors/xhr.ts
Labels: bug

#69 feat: Use Navigation Timing Level 2 to catch perf data
  src/performance/perf.ts
  src/trace/interceptors/fetch.ts
  src/trace/segment.ts
Labels: enhancement
