Repository apache/skywalking-client-js, pull requests merged in 2021-01, with the labels that each got.

#33 fix: trace perf of spa page
  src/monitor.ts
  src/performance/index.ts
Labels: bug

#32 fix: update parameters in segments
  README.md
  src/errors/ajax.ts
  src/interceptors/xhr.ts
  src/monitor.ts
  src/services/report.ts
  src/trace/segment.ts
  src/types.d.ts
Labels: bug

#34 feat: add tags for spans
  README.md
  src/monitor.ts
  src/trace/segment.ts
  src/types.d.ts
Labels: enhancement

#35 docs: update 0.3.0 changes
  CHANGES.md
Labels: documentation

#36 Prepare the official release
  .github/workflows/build.yml
  README.md
  dist/LICENSE
  dist/NOTICE
  licenses/LICENSES-fetch.txt
  licenses/LICENSES-js-base64.txt
  package-lock.json
  package.json
  release.md
  tools/check-license-header.py
Labels: documentation

#38 docs: update year for NOTICE
  NOTICE
Labels: documentation

#40 fix: update stack and message in logs
  README.md
  src/errors/ajax.ts
  src/errors/js.ts
  src/errors/promise.ts
  src/errors/resource.ts
  src/errors/vue.ts
  src/services/base.ts
  src/services/types.d.ts
Labels: bug
