Repository apache/skywalking-client-js, pull requests merged in 2022-04, with the labels that each got.

#78 fix: update metric and events
  src/performance/fmp.ts
  src/performance/index.ts
  src/services/task.ts
  src/trace/segment.ts
Labels: bug

#80 Remove ServiceTag
  src/trace/interceptors/fetch.ts
  src/trace/interceptors/xhr.ts
  test/e2e.yaml
  test/expected/dependency.yml
  test/expected/trace-detail.yml
Labels: enhancement

#79 fix: update fmp metric
  CHANGES.md
  README.md
  src/performance/fmp.ts
  src/services/constant.ts
  src/trace/type.d.ts
Labels: bug

#81 refactor: update perf functions
  package.json
  src/monitor.ts
  src/performance/fmp.ts
  src/performance/index.ts
  tsconfig.json
Labels: chore

#84 build: bump packages and update package-lock with npm v8
  .github/workflows/build.yml
  package-lock.json
Labels: dependencies

#86 feat: reset custom configurations when the page router changed for SPA
  src/errors/ajax.ts
  src/errors/frames.ts
  src/errors/js.ts
  src/errors/promise.ts
  src/errors/resource.ts
  src/errors/vue.ts
  src/monitor.ts
  src/trace/interceptors/fetch.ts
  src/trace/interceptors/xhr.ts
  src/trace/segment.ts
Labels: enhancement
