Repository apache/skywalking-client-js, pull requests merged in 2022-10, with the labels that each got.

#97 Add Security Notice
  README.md
Labels: documentation

#98 build(deps): bump dependencies
  package-lock.json
  package.json
  server.js
Labels: dependencies

#101 feat: support adding custom tags to spans
  README.md
  src/monitor.ts
  src/trace/interceptors/fetch.ts
  src/trace/interceptors/xhr.ts
  src/types.d.ts
Labels: enhancement

#102 feat: validate custom parameters for `register`
  src/errors/vue.ts
  src/monitor.ts
Labels: enhancement

#103 docs: update changes and version
  CHANGES.md
  package-lock.json
  package.json
Labels: documentation
