Repository apache/skywalking-client-js, pull requests merged in 2023-10, with the labels that each got.

#117 fix: pin selenium version and update license ci
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .licenserc.yaml
  test/docker/Dockerfile.generate-traffic
  tools/check-license-header.py
Labels: bug, chore

#116 fix: fix reading property from null
  src/performance/fmp.ts
Labels: bug

#118 docs: remove QQ group from README, update version
  README.md
  package-lock.json
  package.json
Labels: documentation
