Repository apache/skywalking-client-js, pull requests merged in 2025-02, with the labels that each got.

#153 fix: The caught fetch request does not work when it receives a URL
  src/trace/interceptors/fetch.ts
Labels: bug

#155 Adjust readme for incoming 1.0 release
  README.md
Labels: documentation

#154 Fix the`FMP` metric
  src/performance/fmp.ts
  src/performance/index.ts
  test/docker/index.js
  test/expected/error-log.yml
Labels: bug

#156 Bump up test ui
  test/docker/Dockerfile.test-ui
  test/docker/index.js
  test/docker/nginx.conf
  test/env
Labels: enhancement

#157 feat: detect supported browser APIs for core web vitals
  README.md
  src/performance/index.ts
  src/services/apiDetectSupported.ts
Labels: enhancement

#158 Distinguish empty data
  src/performance/index.ts
Labels: enhancement
